BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Hotel] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] NVARCHAR(200) NOT NULL,
    [address] NVARCHAR(500),
    [phone] NVARCHAR(50),
    [logoUrl] NVARCHAR(500),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Hotel_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Hotel_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[User] (
    [id] INT NOT NULL IDENTITY(1,1),
    [email] NVARCHAR(255) NOT NULL,
    [password] NVARCHAR(255) NOT NULL,
    [name] NVARCHAR(200) NOT NULL,
    [role] NVARCHAR(50) NOT NULL CONSTRAINT [User_role_df] DEFAULT 'RECEPTIONIST',
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [User_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    [hotelId] INT NOT NULL,
    CONSTRAINT [User_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [User_email_key] UNIQUE NONCLUSTERED ([email])
);

-- AddForeignKey
ALTER TABLE [dbo].[User] ADD CONSTRAINT [User_hotelId_fkey] FOREIGN KEY ([hotelId]) REFERENCES [dbo].[Hotel]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
